from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


class DashboardGenerator:
    """
    Generates Streamlit-compatible data structures and static Plotly figures
    for the Historical Simulation dashboard page.
    """

    def generate_equity_chart_data(self, equity: list[float]) -> dict:
        if not equity:
            return {}
        arr = np.array(equity)
        peak = np.maximum.accumulate(arr)
        dd   = (peak - arr) / np.maximum(peak, 1) * 100
        return {
            "equity":    arr.tolist(),
            "drawdown":  dd.tolist(),
            "peak":      peak.tolist(),
        }

    def generate_monthly_heatmap(self, monthly_returns: dict) -> pd.DataFrame:
        if not monthly_returns:
            return pd.DataFrame()
        rows: dict[int, dict[int, float]] = {}
        for period, ret in monthly_returns.items():
            try:
                parts = str(period).split("-")
                yr, mo = int(parts[0]), int(parts[1])
                rows.setdefault(yr, {})[mo] = ret
            except Exception:
                continue
        if not rows:
            return pd.DataFrame()
        df = pd.DataFrame(rows).T
        df.columns = [f"M{c:02d}" for c in df.columns]
        return df.fillna(0)

    def generate_return_distribution(self, pnl_pcts: list[float], bins: int = 30) -> dict:
        if not pnl_pcts:
            return {}
        arr   = np.array(pnl_pcts)
        hist, edges = np.histogram(arr, bins=bins)
        return {
            "counts":      hist.tolist(),
            "bin_centers": ((edges[:-1] + edges[1:]) / 2).tolist(),
            "mean":        float(arr.mean()),
            "std":         float(arr.std()),
            "skew":        float(pd.Series(arr).skew()),
        }

    def generate_rolling_sharpe(
        self, pnls: list[float], window: int = 30
    ) -> dict:
        if len(pnls) < window:
            return {}
        s = pd.Series(pnls)
        roll = s.rolling(window).apply(
            lambda x: x.mean() / x.std() * (252 ** 0.5) if x.std() > 0 else 0, raw=True
        )
        return {"rolling_sharpe": roll.dropna().tolist()}

    def generate_regime_breakdown(self, regime_series: pd.Series) -> dict:
        if regime_series.empty:
            return {}
        counts = regime_series.value_counts()
        total  = len(regime_series)
        return {
            str(k): {"count": int(v), "pct": round(v / total * 100, 1)}
            for k, v in counts.items()
        }

    def generate_correlation_heatmap_data(
        self, correlation_matrix: dict[str, dict[str, float]]
    ) -> dict:
        if not correlation_matrix:
            return {}
        labels = list(correlation_matrix.keys())
        matrix = [
            [correlation_matrix[r].get(c, 0) for c in labels]
            for r in labels
        ]
        return {"labels": labels, "matrix": matrix}

    def generate_stress_test_chart(self, stress_rows: list[dict]) -> dict:
        if not stress_rows:
            return {}
        return {
            "scenarios":    [r.get("scenario", "?") for r in stress_rows],
            "max_loss":     [r.get("max_loss_pct", 0) for r in stress_rows],
            "survived":     [r.get("survived", False) for r in stress_rows],
            "recovery":     [r.get("recovery_days", 0) for r in stress_rows],
        }

    def generate_walk_forward_chart(self, folds: list[dict]) -> dict:
        if not folds:
            return {}
        return {
            "fold_ids":     [f.get("fold_id", i) for i, f in enumerate(folds)],
            "train_sharpe": [f.get("train_sharpe", 0) for f in folds],
            "test_sharpe":  [f.get("test_sharpe", 0) for f in folds],
            "overfit_flag": [f.get("overfitting", False) for f in folds],
        }

    def export_streamlit_page(self, report: dict, output_path: Path | None = None) -> str:
        """Generate a standalone Streamlit page snippet for embedding."""
        symbol   = report.get("symbol", "?")
        strategy = report.get("strategy", "?")
        score    = report.get("summary", {}).get("quality_score", 0)
        b        = report.get("backtest", {})

        code = f'''import streamlit as st
import json, pathlib

# Auto-generated by DashboardGenerator
st.title("Historical Simulation — {symbol} / Strategy {strategy}")
st.metric("Quality Score", "{score}/100")

cols = st.columns(4)
cols[0].metric("Total Return", "{b.get('total_return', 0):.2f}%")
cols[1].metric("Sharpe", "{b.get('sharpe', 0):.3f}")
cols[2].metric("Max DD", "{b.get('max_drawdown', 0):.2f}%")
cols[3].metric("Win Rate", "{b.get('win_rate', 0)*100:.1f}%")
'''
        if output_path:
            output_path.write_text(code, encoding="utf-8")
        return code
